# Configurations for generate
data-generation:
    #Packer executable path
    executable_path: /usr/local/bin/packer 
    #Time in seconds to run the generation
    time: 600 
    #Location of attack machine
    attack_machine_path: data_generation/virtual-machines/attack.ova 
    #Location of target machine
    target_machine_path: data_generation/virtual-machines/target.ova
    #Attack machine ssh username
    attack_username: root
    #Attack machine ssh password
    attack_password: yeet
    #Attack machine IP
    attack_ip: "192.168.0.14"
    # IP of target machine to filter from
    filter_ip: "192.168.0.15" 
    # Interface you are bridging
    interface: en0
# Configurations for processing
data-processing:
    # Location to store data
    dataset_path: dataset.csv
    # Filter to process to
    filter: 
# Configurations for modeling
data-modeling:
    # Path to store model
    model_path: IDS.joblib
    # Classes found in dataset
    classes:
        - normal
        - synflood
        - udpflood
        - pshackflood
        - finflood
# Configurations for ids
ids:
    # Place to locate the model
    model: intrusion_detection/IDS.joblib

